theme: jekyll-theme-minimal
title: Herramientas Computacionales
description: Seminario de posgrado
logo: https://github.com/agusnieto77/Sem-HCACSo/blob/main/docs/img/seminario.png
show_downloads: false
