theme: jekyll-theme-minimal
title: Sem-HCACSo
description: Herramientas computacionales para el análisis de la conflictividad social
logo: https://estudiosmaritimossociales.org/seminario03.png
show_downloads: false
