theme: jekyll-theme-minimal
title: Sem-HCACSo
description: Pagina web del seminario de posgrado Herramientas computacionales para el análisis de la conflictividad social
logo: https://estudiosmaritimossociales.org/seminario3.png
show_downloads: true
